experiment_name=grpo_human_body

CUDA_VISIBLE_DEVICES=0,1 accelerate launch --config_file configs/deepspeed/zero2_2gpu.yaml \
    -m reward_model_train.cli.grpo_train \
    --dataset_name "/m2v_intern/wangqunzhong/research/asset/kwai_data/dataset" \
    --output_dir log/model_checkpoints/$experiment_name \
    --remove_unused_columns False \
    --learning_rate 5e-6 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --num_iterations 8 \
    --num_generations 16 \
    --model_name_or_path "Qwen/Qwen2.5-VL-7B-Instruct" \
    --report_to "wandb" \
    --logging_steps 1 \
    --save_strategy steps \
    --save_steps 100 \
    --num_train_epochs 5 \
    --use_peft True \
    --lora_task_type "CAUSAL_LM" \
    --lora_r 64 \
    --lora_target_modules "q_proj" "v_proj" \
    --lora_alpha 32 \
    --lora_dropout 0.1 \
    --log_completions True \
    --data_pipeline "qwen2.5-humanbody-grpo" \
    --data_select_ratio 0.05 \
    --cache_dir "/m2v_intern/wangqunzhong/research/asset/huggingface/model/Qwen/Qwen2.5-VL-7B-Chat" \
    --torch_dtype "bfloat16" \
    --data_source "video" \
    --do_train True \
    --bf16 True \
    --max_completion_length 1024 \
    --fps 8. \
    --max_prompt_length 2048 \
    --run_name $experiment_name
